export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function BoardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section className='flex'>{children}</section>;
}
